project:
  type: website
  output-dir: _site

website:
  title: "Chris Varghese"
  navbar:
    background: white
    foreground: "#4273b5"
    right:
      - text: "Home"
        href: index.qmd
      - text: "Research Themes"
        href: research.qmd
      - text: "Publications"
        href: "https://scholar.google.com/citations?user=rsVXjrMAAAAJ&hl=en"
      - text: "Lab"
        href: "http://srslab.auckland.ac.nz/"
  page-footer:
    center: "© 2026 Chris Varghese"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    page-layout: full
    smooth-scroll: true
